Roll Fletch  (was 158 behind)
5e61088 Add debug-image.sh helper and fix minor issues.
cfbc3fa Revert "Add shell=True to subprocess call when generating version files."
23fc415 Don't delete out before getting docs on mac
1d1a5ac Add shell=True to subprocess call when generating version files.
725f5bd Do not specify destination folder for gsutil
24d0fda Run the service compiler at test time for the old todomvc sample.
4a159f3 Remove the shutdown verb.
feba382 Service compiler: predictably fail if the initial message segment is too small.
60d1d21 Service compiler: generate simple_todo test output files in a temporary directory.
90fe396 Add missing space to download_from_google_cloud_storage command
803f288 Run the service compiler at test time for the multiple services tests.
e6dc075 Add test for stacktrace decoding of snapshot stack traces
8401e8f Service compiler: generate test sources in the temporary test directory.
719cab9 Add Documentation generation to the bots
9fd40cb Revert "Simplify generation of version.cc."
ad5280e Simplify generation of version.cc.
414b346 Make failure to grow stack consistently cause stack overflow exception.
c6e23fa Refactor relocation support into a service that can be used from within the VM.
3858b86 Add library level doumentation to some packages
5ab0b71 Create a temporary test-output directory for output generated during tests.
d67da55 Initial implementation of mark-sweep garbage collector.
49c7df5 Add tool to print the current version as given in the tools/VERSION file
6b232f1 Install a Avahi service configuration file with the Fletch agent
8f5a9cf Add specialized version of the dart sdk that we can use to build documentation.
3704793 Add pubspec.yaml files for our packages
1712ead Use program offset printing only if loaded from snapshot *and* compacted
bb3ae90 Snapshoting: In addition to writing a snapshot write [ProgramInfo] metadata containing symbol information.
0715110 Avoid a warning due to bug in Dart SDK
bc29f6b Add mDNS discovery to the Fletch compiler
5c4d55e Add multiple results and timeout handling to the Mac OS mDNS native extension
97735de Update the mDNS native extension for Mac OS to handle PTR and SRV records
93ecf74 Don't hang on some of the interactive debugger commands.
791be3e Update the mDNS command line tools in the mdns package
3043bb8 Minor fixes to the mDNS package
935bb76 Avoid generating a stub for matching positional optional parameters
8523059 Mark tests as related to bug 295
345665e Service compiler: report errors for invalid compilations in service_tests.
b892e4b Expand the stack to contain two extra (for now empty) slots on the stack.
b7c6516 Only promote 64 bit builds
c7d2763 Make the flash_sd_card script work with spaces in the path
c789088 Add support to rebase the intrinsics table.
c8aba44 Update LK status for uri_base
bf986a9 Make FletchNoSuchMethodError a built-in class and thereby expose it to the runtime
89fb0b4 Calculate function/class offsets in the program heap ....
e19ea63 Remove unnecessary scheduler coroutine & stack in Fiber implementation
2bd4d1d Mark tests as related to bug 294
f198731 Mark tests as related to bug
5247310 Add test for bug #292
8ed2a18 Improve resource record implementation in the mdns package.
155714d Add the fletch package to the SDK
a0a5a93 Use the URL from the build bot to fetch the Fletch Raspbian image
f9d4adb Test bad_function_4 is now passing
ad37435 Updating status file after closed issue.
9231bbf Add location information to info reporting and lower case error type.
d688908 Check list type parameter is not string
a8bae7d Cleanup of raspbian image generation script
c0043be Launch fletch-vm from same directory as C++ client
1cdcc3d Bump version to 0.2 on master
7fdaea8 Fix issues with flash_sd_card
d8cabb9 Mark regexp/global_test as slow on asan
b2cbbe9 Change update_version_gyp.py to support local incremental builds
981946f Only throw UnexpectedExitCode if checkExitCode is true
6c1d0bb Fix ssh key file checking for qemu image interaction
69d1720 Temporarily disable normal exception handling when the qemu image is not up, give more time up front
8baeecf Don't try to read from the qemu process on every ssh try
21b46c8 Put qemu log to a file instead of stdout
d224660 Add logging of the qemu output to sys.stdout on the bot
2bbea01 Fix comment about number of times we retry connecting to qemu
ec79e6a Retry mounting on Mac when writing the SD card
4c61a74 Give qemu more time to start up, the bots are slower than local
e56d275 Add third_party/raspbian content to .gitignore
57c5902 Fix a few grammar errors.
25bc800 Add debugging support to fletchc blaze wrapper.
70e8070 Use checked in qemu for running the raspbian preperation step
33005f8 Make the sdk bots create and archive fletch enabled raspbian images
4898c14 Add slightly modified raspbian image to google cloud storage
83775f8 Temporarily limit which signals are intercepted
fd6af67 Don't include the path when zipping the Fletch Raspbian image
35d25bf Merge pull request #276 from kaendfinger/patch-1
6696bcf Add an option for the log file to the flash_sd_card script
e4b44bb Minor updates th the SD card flash script
be5378b Add a tool to download the Fletch Raspbian image and flash it to an SD Card.
3615557 Better messages for servicec errors
8a21c8a Free buffer in PosixSystem.info().
a51e673 Don't reschedule periodic timers canceled in the callback.
3033b50 Mark lib/async/catch_errors12_test as flaky on arm
cf06e3e Add a script to create a raspbian image with the agent installed without using sudo.
7daf32c Out filename does not depend on in service name
9499898 Suppress errors in newly activated tests to get the bots green
e9d48a8 Only access parameters in the compiler, through load-/storeParameter.
21b68de Please the compiler (sigh).
67cb7fa Stop putting tables of bytecode information in RAM and make the table representation more compact.
e61ba63 Enable test suites that were not run.
9c6dda1 Remove .jar generation in Java backend
98e493a Check the fletch version used in the compiler matches the one used by the agent.
ae31028 Only remap from SIGINT to SIGTERM on Raspbian wheezy.
961bd9f Rename invokes (normal->unfold, vtable->), and rename vtable -> dispatch table.
1e0620a Add support for PortableSize of all heap objects & snapshot support for it
79bf5d3 Add begin struct and begin service markers
9b6223b Don't keep vm-<pid>.[port|pid] files around.
4d299cb Add constant to _functionToMode in raspberry_pi library.
9271aad Add Raspbian configuration service
05a4392 Encode bytecode size in snapshots *without* alignment
c55aad3 Do not iterate over session program roots when writing/reading snapshots
42cddde Add script to create a raspbian image that can be loaded into qemu
1193c93 Add some more files to .gitignore.
740cec7 Fix dispatch offset on arm, for DoInvokeTestNoSuchMethod.
93a178e Cleanup fix for bug 221.
c5dfe7f Remove the dispatch table and 'fast' invoke bytecodes, and instead introduce `invoke on-such-method` bytecodes.
f85fea1 Fix erronous capture of this for closures in constructor initializres.
d68fab0 Update status file
380a382 Revert "Revert "Add support for reporting the fletch version via the agent.""
3da3a77 Update status file
246dc6c Fix golem tests for mac asan builds.
f5339c7 Update status file
337ee78 Allow test to also pass.
350e356 Re-land "Extend the mDNS package with a native extension used on Mac OS"
ed18616 Revert "Add support for reporting the fletch version via the agent."
91fed6f Cache instance accessors in FletchSystem
5bf1afe Disallow service and struct name clashes
a649f7b Add support for reporting the fletch version via the agent.
f915778 Fix library name and import
9f06dc2 Add bundle with the linux kernel compiled so that we can run on the raspbian
5bd9603 Change model.dart to todo_model.dart
340b904 Allow language/closures_initializer2_test to fail at runtime rather than crash ..
891b7b5 Split SimpleTodo.java to TodoController.java
0f2727b Test no longer crashes with LK page allocator
007ef9e Reapply: Add test that mimics our Golem benchmarking infrastructure.
6fd4f29 Revert "Extend the mDNS package with a native extension used on Mac OS"
993c30a Fix free before use in fletch command line tool.
62d58e7 Let visitForTest accept one fall-through label (null) ...
a266dd5 Throw correct StackOverflowError object on stack overflow.
7b02aed Extend the mDNS package with a native extension used on Mac OS
f5f9558 Revert test for Golem infrastructure. Doesn't work on Mac.
d0699ba Make the creation of the agent deb a step on the bots
f7082f8 Add test that mimics our Golem benchmarking infrastructure.
95ebb8c Update DEPS to remove use of dart:profiler from dart2js.
57ff8b0 Support running only x64 on the bots
33d3cd8 Correctly identify unhandled functions
388b75b FletchSystem debugger
d94f04e Fix some ASAN leaks.
2312b61 Check the Fletch VM's exit code
98c8142 Don't minify AST nodes in stack traces
185deec Fix warnings test.
4fd55dd Go back to using run.dart instead of 'fletch export' to create snapshots of the fletch agent for the SDK.
acc6815 Add scripts for running the fletch compiler and service compiler on blaze.
967c7d6 Package .java output as a .jar
5c0e5ec Get Fletch version from VM if compile-time constant not provided
75f9347 Actually fix the failing mac agent tests.
c37321e Add file describing the resources we need for benchmarking
a367f88 Determine "last alive process" before deleting it
525686d Fix failing agent test on mac by using SIGTERM (stopVm) instead of SIGINT.
328d4ac Use the new page allocator API on LK
6978228 Add x-upgrade action to fletch.
9c621ba Roll LK to get fix to static asserts
efbb4a2 Revert "Revert "Add first tests for Fletch Agent.""
7f9ca7d Make the fletch agent messages use 4 bytes for vm ids (aka. pids).
3b46ec4 Fix issue with flags and errnos on Mac being different than linux.

BUG=

Review URL: https://codereview.chromium.org/1439843002 .